### ISSUE TITLE
OOM on hotplug failure

### ISSUE THREAD

**Issue by vadim2404** [neondatabase/autoscaling#116]
## Logs, links
-

**Comment by sharnoff** [comment]
Case from a user where this _may_ have happened: https://neondb.slack.com/archives/C03TN5G758R/p1688207511789269

**Comment by vadim2404** [comment]
1. #451 
2.  try to reproduce it (create an automated test)
3.

**Comment by stradig** [comment]
This has not seen recently since updating the kernel.
