### ISSUE TITLE
Impossible to scale memory more than x60 

### ISSUE THREAD

**Issue by vadim2404** [neondatabase/autoscaling#117]
Original title: "vhost backends exhausted"

## Steps to reproduce
related to large VMs

## Logs, links
-

**Comment by sharnoff** [comment]
Not sure if this still, but there's definitely still issues. Here's the latest:

I tried creating a VM on staging with 1Gi memory slots, min=1, max=80 - and then scaling up to 40, then 60 memory slots. 40 was fine, but trying to scale up to 60 resulted in a kernel panic. ([logs link](https://neonprod.grafana.net/explore?schemaVersion=1&panes=%7B%22cl0%22:%7B%22datasource%22:%22xHHYY0dVz%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcluster%3D%5C%22dev-eu-west-1-zeta%5C%22,namespace%3D%5C%22default%5C%22,container%3D%5C%22neonvm-runner%5C%22,pod%3D%5C%22sharnoff-vm-test-5gmdw%5C%22%7D%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22xHHYY0dVz%22%7D,%22editorMode%22:%22code%22,%22maxLines%22:5000%7D%5D,%22range%22:%7B%22from%22:%221705962795973%22,%22to%22:%221705962804077%22%7D%7D%7D&orgId=1)).

Trying to replicate locally (on a machine with 32GiB RAM), I decreased the memory slot size to 128Mi, and eventually the same kernel panic happened. It's proceeded by OOM kills triggered when hotplugging, and many of the hotplugging attempts fail (even though the VM's .status.memory is updated as if it were successful).

So I suspect that this "vhost backends exhausted" issue - which was previously the error we'd get from QEMU when trying to plug in ~60 memory slots - is _probably_ no longer an issue.

**Comment by Omrigan** [comment]
The x60 limitation comes from the need to place bookkeeping for ZONE_MOVABLE memory into ZONE_NORMAL [1]. 

Info from @kelvich: it is actually possible to plug more than x60 of the original memory size, we just have to plug it not as ZONE_MOVABLE, but as ZONE_NORMAL. This means kernel doesn't guarantee it will be able to unplug that memory later. Although it is unclear if the unplug will be possible in practice. 

So I see two approaches:
1. Plug some memory as ZONE_NORMAL and be prepared compute won't be able to downscale
2. Have bigger initial memory/dimm slot, and inflate the baloon to give it back to host 

virtio-mem might come in handy (see #705). Although I am not aware of a direct impact on this task. 

[1]: https://docs.kernel.org/admin-guide/mm/memory-hotplug.html#zone-imbalances
