### ISSUE TITLE
e2e migration test is flaky

### ISSUE THREAD

**Issue by sharnoff** [neondatabase/autoscaling#120]
Had [a CI failure] on #110 that didn't make sense, and re-running didn't fail. Not sure if this was due to external conditions or a bug. AFAICT this was the responsible log line (in the NeonVM controller):

> {"level":"error","ts":"2023-03-31T06:40:22.445Z","logger":"controller.virtualmachinemigration","msg":"Failed stop hypervisor in source runner pod","reconciler group":"vm.neon.tech","reconciler kind":"VirtualMachineMigration","name":"example","namespace":"kuttl-test-expert-weasel","error":"read tcp 10.244.162.130:45076->10.244.162.135:20183: read: connection reset by peer","stacktrace":"github.com/neondatabase/autoscaling/neonvm/controllers.(*VirtualMachineMigrationReconciler).Reconcile\n\t/workspace/neonvm/controllers/virtualmachinemigration_controller.go:186\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}

https://github.com/neondatabase/autoscaling/actions/runs/4572248349/jobs/8071305058#step:12:7103

(this failure seems to be repeated until the test timed out)

[a CI failure]: https://github.com/neondatabase/autoscaling/actions/runs/4572248349/jobs/8071305058

cc @cicdteam / @bayandin any ideas?

**Comment by sharnoff** [comment]
Another, completely different case, from kuttl logs:

> case.go:366: Internal error occurred: failed calling webhook "mvirtualmachine.kb.io": failed to call webhook: Post "[https://neonvm-webhook-service.neonvm-system.svc:443/mutate-vm-neon-tech-v1-virtualmachine?timeout=10s](https://neonvm-webhook-service.neonvm-system.svc/mutate-vm-neon-tech-v1-virtualmachine?timeout=10s)": context deadline exceeded

https://github.com/neondatabase/autoscaling/actions/runs/4589958144/jobs/8105191759#step:11:248

I've ran into this locally when the cluster was degraded (in a vague sense) due to exceptionally high system load. When that happened, the load was from building images, so re-running after the images were fully built resolved the problem.

From times I've seen this before, best I can tell is that leader elections for a number of components were failing due to the high system load (because their network connections weren't making it through, or something), and so the crash loop backoff was actually in effect. Crucially, the cluster did not fully recover after sitting for a while — all pods were up and running, but the same webhook timeout thing was happening.

**Comment by sharnoff** [comment]
I've been running into this relatively frequently. AFAICT it typically happens when there's >1 e2e job running at the same time, but I'm not sure if that's related or just due to statistics.

**Comment by bayandin** [comment]
Is it still flaky?
I haven't seen its failures for a while (but I haven't worked much on the project)

**Comment by sharnoff** [comment]
I think migration is no longer flaky. Now just autoscaling, I think. I'll open a separate one for that.
