### ISSUE TITLE
Use "proper" web framework for HTTP servers

### ISSUE THREAD

**Issue by sharnoff** [neondatabase/autoscaling#13]
See: https://github.com/neondatabase/autoscaling/pull/8#discussion_r1065054595

There's a few places we have HTTP servers:

* pkg/plugin/run.go: `(*AutoscaleEnforcer) runPermitHandler`
* ~~pkg/agent/serve.go: `startInformantServer`~~
* ~~cmd/informant/main.go: `main`~~
* pkg/plugin/dumpstate.go: `(*AutoscaleEnforcer) startDumpStateServer`
* pkg/agent/dumpstate.go: `(*agentState) StartDumpStateServer`

(time of writing: 2023-01-10, commit 65d1528f46682086345cb28920204436e7600be1)
(updated: 2023-10-12, commit 166c8d01fa12c1d8eac2a586403bd83648349d73)

Ideally we'd have something less home-grown here, to reduce custom code & leverage existing wisdom.

**Comment by sharnoff** [comment]
This is now just the scheduler plugin, because the vm-informant was removed in #442, and the agent's HTTP server (which only existed to handle connections from the informant) was removed in #506.

**Comment by stradig** [comment]
We are okay with the current state, the code is very readable.
