### ISSUE TITLE
build: commit messages are hard to "properly" escape for ldflags

### ISSUE THREAD

**Issue by sharnoff** [neondatabase/autoscaling#16]
## Background

Currently our dockerfiles use ldflags to embed git information into the built images — e.g.:

https://github.com/neondatabase/autoscaling/blob/59fce39dc15ec1ab2d3a4ac387aa1e6a4a5cf334/build/autoscaler-agent/Dockerfile#L15-L21

However, there's quoting issues with this approach:

https://github.com/neondatabase/autoscaling/blob/59fce39dc15ec1ab2d3a4ac387aa1e6a4a5cf334/scripts-common.sh#L38-L41

It can't be solved by adding extra backslashes, unfortunately.

This actually caused a release failure on 30c8bc9755e7caa284bbdd5714bf708098d71471, fixed in 3387ae4a0ce5cc2345000484a9a5e43a60f2548c.

## Desired outcome

There's a couple options here. Either we switch away from ldflags and use go:embed (e.g., as in https://levelup.gitconnected.com/a-better-way-than-ldflags-to-add-a-build-version-to-your-go-binaries-2258ce419d2d) or we use cleaner escaping (e.g., base64).

I think the base64 approach _may_ ultimately be a nicer solution here, but it's a little funky to deal with (and may run into cross-platform issues w.r.t. behavior of the `base64` command). However, the big upside is that it's easier to respect git worktrees with ldflags vs. go:generate (or whatever we'd use to make the embedded files for go:embed).

**Comment by tychoish** [comment]
why not just use `git describe`?

**Comment by sharnoff** [comment]
Ran into this again, temporarily fixed in a4ed1c0e17288bf91b1d43246ab13d523b050346, opened #122 because yeah, `git describe` is better.
