### ISSUE TITLE
NeonVM logs on grafana

### ISSUE THREAD

**Issue by koivunej** [neondatabase/autoscaling#166]
https://neonprod.grafana.net/d/IJSLHBOnk/neon-logs-compute-nodes?orgId=1 cannot currently be used to view NeonVM logs due to the dashboard searching for `{app=~"$project", pod=~"compute-node-.*"}`. I dislike the dropdowns on that dashboard, but it's probably the first thing someone will try if the logs need to be found.

What seems to work for both is `{pod=~"compute-node-$project-.*"}` but unsure if this is possible with grafana. NeonVM logs seem to always have `{app="NeonVM"}` instead of the project. Perhaps that is easier to fix than to have grafana string interpolate.

All other labels should be aligned at the same time, I think there is some dashboard searching with `{job="default/$endpoint"}`.

Labels of non-neonvm and neonvm random messages for comparison:

```
app         compute-node-ep-shy-term-170754
cluster     prod-eu-central-1-gamma
container   postgres-exporter
job	    default/compute-node-ep-shy-term-170754
namespace   default
neon_env    prod
neon_region eu-central-1
node_name   ip-10-7-35-96.eu-central-1.compute.internal
pod         compute-node-ep-shy-term-170754-74b8c467f9-xv8n6
stream      stderr
```

neonvm:
```
app         NeonVM
cluster     prod-us-east-2-delta
container   runner
job         default/NeonVM
namespace   default
neon_env    prod
neon_region us-east-2
node_name   ip-10-8-21-55.us-east-2.compute.internal
pod         compute-node-ep-muddy-band-755607-4xmmw
stream      stdout
```

**Comment by koivunej** [comment]
Additionally noted that the number of computes is on [Neon / Compute metrics](https://neonprod.grafana.net/d/000000039/neon-compute-metrics?orgId=1&refresh=5m) off from https://console.neon.tech/admin/endpoints?sort=id&order=desc&current_state=active, for example right now:
- dashboard 567
- console 581

**Comment by sharnoff** [comment]
This was marked as done on 2023-07-12, but not actually closed.
