### ISSUE TITLE
no observability into neonvm reconcile failures (needs metrics!)

### ISSUE THREAD

**Issue by sharnoff** [neondatabase/autoscaling#247]
Problems like #243 would be easier to detect and debug if we had more observability into the neonvm controller, specifically around reconciliation failures.

Off-hand, I see two ways of doing this (but there are definitely more!)

1. Increment some counter when reconciling fails (i.e. global rate of failed reconciliation)
2. Globally track how many VMs are failing to reconcile, expose this as a gague
    - This is more work (and uses more memory, and has the "multiple sources of truth" problem), but is maybe closer to what we actually care about.

We can also do both options, because each option has cases that it will report but the other won't.

**Comment by shayanh** [comment]
I think the `rate` of the first metrics is almost the second metrics. Isn't it?

**Comment by sharnoff** [comment]
status: Second half is almost done, PR to come this week
