### ISSUE TITLE
vm-informant is only configurable at compile time

### ISSUE THREAD

**Issue by sharnoff** [neondatabase/autoscaling#266]
Currently all the vm-informant's config is defined as compile-time constants, here:

https://github.com/neondatabase/autoscaling/blob/fed87ff1ee1e51efe850d07f7a986f8e1fd4ddb8/pkg/informant/consts.go#L23-L43

This means that any fix to an issue with the vm-informant's config would require (a) a new autoscaling release _and_ (b) a new `neondatabase/neon` release (to update the VM compute node image).

Something like having a config file set by the control plane would allow for quick, per-user fixes (maybe just updating an entry in the DB) without requiring chaining several releases.

**Comment by sharnoff** [comment]
I think this will be resolved (somewhat; functionality moving away from the vm-informant itself) with #362? cc @fprasx to confirm

Either way, something to keep in mind for the vm-monitor

**Comment by fprasx** [comment]
Yes, this functionality will be moved into the vm-monitor. I'm under the impression that the control plane sends things to `compute_ctl` on startup so this should be configurable that way.

**Comment by sharnoff** [comment]
vm-informant no longer exists, as of #442 - issue no longer necessary (or, at least, it should be handled in `neondatabase/neon`, for the vm-monitor)
