### ISSUE TITLE
Follow-up tasks from #25

### ISSUE THREAD

**Issue by sharnoff** [neondatabase/autoscaling#27]
Items from review:

- [x] ~~Sentry integration - both in general and for `spawnBackgroundWorker` ([link](https://github.com/neondatabase/autoscaling/pull/25#discussion_r1084733617))~~
  - No longer necessary; alerting on metrics is sufficient.
- [x] Replace unusual HTTP constants (e.g. 409 in `pkg/informant`) with their constants in `net/http` ([link](https://github.com/neondatabase/autoscaling/pull/25#discussion_r1084734000))
  - Will be mostly handled once the informant is removed/deprecated
- [x] `pkg/agent` should be split into multiple packages ([link](https://github.com/neondatabase/autoscaling/pull/25#discussion_r1084735705))
  - Implemented by https://github.com/neondatabase/autoscaling/pull/289, https://github.com/neondatabase/autoscaling/pull/309
- [x] agent<->informant protocol checks should be implemented in `pkg/api` ([link](https://github.com/neondatabase/autoscaling/pull/25#discussion_r1084735906))
  - implemented by #30
- [x] Add tests to `pkg/agent` (particularly around `Runner`) ([link](https://github.com/neondatabase/autoscaling/pull/25#discussion_r1084737232))
  - Replaced by #199
- [x] #45
- [x] `(*Runner).updateVMResources` loop body should be extracted into separate function ([link](https://github.com/neondatabase/autoscaling/pull/25#discussion_r1084738213))
  - Obviated by https://github.com/neondatabase/autoscaling/pull/113
- [x] `(*Runner).doMetricsRequestIfEnabled` code between Lock() and Unlock() should be a separate method ([link](https://github.com/neondatabase/autoscaling/pull/25#discussion_r1084738683))
  - Replaced by #472

Item from the PR, before reviewing:

- [x] https://github.com/neondatabase/autoscaling/pull/51 ([comment](https://github.com/neondatabase/autoscaling/blob/bc1f146d9291e8c1ccf97855af445f554cbba63e/pkg/agent/runner.go#L605-L607), [comment](https://github.com/neondatabase/autoscaling/blob/bc1f146d9291e8c1ccf97855af445f554cbba63e/pkg/agent/runner.go#L1681))
- [x] Runner should separately track "confirmed" vs "unconfirmed" VM state ([comment](https://github.com/neondatabase/autoscaling/blob/bc1f146d9291e8c1ccf97855af445f554cbba63e/pkg/agent/runner.go#L83-L87), [comment](https://github.com/neondatabase/autoscaling/blob/bc1f146d9291e8c1ccf97855af445f554cbba63e/pkg/agent/runner.go#L1185-L1186))
  - Obviated by https://github.com/neondatabase/autoscaling/pull/113
- [x] https://github.com/neondatabase/autoscaling/pull/114 — Runner's informant handling and NeonVM handling should be connected to ensure that /suspend doesn't respond until any outstanding NeonVM request is complete, and any NeonVM request requires a live informant ([comment](https://github.com/neondatabase/autoscaling/blob/bc1f146d9291e8c1ccf97855af445f554cbba63e/pkg/agent/runner.go#L1488-L1491))
- [x] https://github.com/neondatabase/autoscaling/pull/316 ([comment](https://github.com/neondatabase/autoscaling/blob/bc1f146d9291e8c1ccf97855af445f554cbba63e/cmd/vm-informant/main.go#L23-L25))
- [ ] ~~informant should wait for a reply to /register response (new message type!) before attempting /resume ([comment](https://github.com/neondatabase/autoscaling/blob/bc1f146d9291e8c1ccf97855af445f554cbba63e/pkg/agent/informant.go#L626-L628))~~
  - Will no longer be necessary once the informant is removed.

Additional items:

- [x] #72 — Use `util.ChanMutex` in place of regular `sync.Mutex` in places where we have deadlock checking.

**Comment by vadim2404** [comment]
let's create additional issues from this task and close that one

@sharnoff

**Comment by sharnoff** [comment]
> let's create additional issues from this task and close that one

done
