### ISSUE TITLE
NeonVM: k8s 1.25 networking follow ups

### ISSUE THREAD

**Issue by cicdteam** [neondatabase/autoscaling#327]
What need to solve after #256 

- [x] update kind version to v0.19.0 (and kind config of node image version)
- [x] update controller manifest `neonvm/config/common/controller/manager.yaml` for resources (request `500m/512Mi`, limit `2000m/1024Mi`)
- [x] remove old (outdated) `NetworkAttachmentDefinition` CRDs in all EKS clusters
- [x] change  `clientcmd.BuildConfigFromFlags`function in IPAM code to  `kubernetes.NewForConfig` to support standard `-kubeconfig` arg and `KUBECONFIG` env variable
- [x] remove `Gateway` and `GatewayStr` from IPAM config struct (as it not used right now)
- [ ] redesigns VM controller to improve reconcile loop (remove re-queueing)
- [x] remove un-necessary checks for `spec.guest.cpus.use` and `spec.guest.memorySlots.use` as these fields filled by defaulter webhook.
- [x] fix `case vmv1.VmScaling` flow in VM controller. CPU and Memory scaling could go async in parallel. Controller should set VM Status Phase to Running only when ether re no any scaling activity.
- [x] redesign `tryUpdateVM` function in VM controller (see [comment](https://github.com/neondatabase/autoscaling/pull/256#discussion_r1224597674)). Probably as part of overall redesign of VM reconcile loop.
- [x] improve CPU sync func (see [comment](https://github.com/neondatabase/autoscaling/pull/256#discussion_r1221965676))
- [ ] redesign QMP queries functions, use subscription to QEMU events instead of `time.Sleep()` and so on
- [ ] change `r.Update()` to `r.Patch()` where it possible in vm and migration controllers

**Comment by sharnoff** [comment]
re-reading a bunch of issues, noticed this line:

> redesign QMP queries functions, use subscription to QEMU events instead of time.Sleep() and so on

This feels very similar to the motivation behind #371 — basically, if everything is written procedurally ("do X; if Y do Z" etc) then it becomes quite difficult to handle event-driven flows like this.

It's _probably_ possible to hack together QEMU events under the current architecture. Longer-term, maybe we want to do something similar to #371 (i.e. implement the logic with a pure function that says what to do, then feed events into it)

**Comment by vadim2404** [comment]
create separate issues from undone items and close this one, @vadim2404

**Comment by sharnoff** [comment]
Closing. Remaining items are mostly covered by #733 and #742.
