### ISSUE TITLE
Set up metal nodes in us-west-2 and us-east-1 regions

### ISSUE THREAD

**Issue by vadim2404** [neondatabase/autoscaling#328]

**Comment by stepashka** [comment]
how urgent is this?
does this unblock one of the Epics?
could you add some more context here?

**Comment by vadim2404** [comment]
It's needed to have autoscaling in all our regions. It's not urgent yet, because of pricing

**Comment by cicdteam** [comment]
Now it tracked in aws repo https://github.com/neondatabase/aws/issues/398

**Comment by sharnoff** [comment]
Closing this as it's been completed (and also shown as such in the aws repo epic)
