### ISSUE TITLE
deploy consistent locking discipline. 

### ISSUE THREAD

**Issue by tychoish** [neondatabase/autoscaling#34]
In reading through the agent code, it's not particularly straight forward (unless you read the comments) which locks you need to be holding to call a specific function. There are some changes to the concurrency model that we might want to deploy in the future (e.g. fewer locks, locks only protect fields in their own structs, etc,) but I think we shouldn't let the perfect be the enemy of the good, and in that spirit... 

I would propose the following idiom:
> No exported (public) function or method requires that the caller hold a specific lock and we should assume that they are safe to call from any go routine. Un-exported/private functions and methods should generally be responsible for holding/managing the scope of their locks (or not needing locks). If it's imperative that the caller of a private function hold a lock the word `unsafe` should appear in the function or method name.

**Comment by sharnoff** [comment]
I think I'm _generally_ in favor of this. There's some kind of complex untangling that'd have to take place for that to work, and there's some existing behaviors (in autoscaler-agent, in particular) that are hard to replicate while adhering to this — stuff to be mindful of.

It seems like this is closely related to the "pkg/agent should be split into multiple packages" item from #27 — It'd be good to keep this in mind while doing that. Probably doesn't make sense to try and do this before splitting stuff up more :)

**Comment by tychoish** [comment]
I think the "reogranize/split the package" might actually depend on doing this because right now the splits would have to be centered on specific mutexes rather than on stronger abstractions, or you'd end up doing a lot of mutex rearranging in order to split the packages.

**Comment by sharnoff** [comment]
Oooh, that's a good point. Thinking some more, it seems like these are heavily intertwined. Seems like realistically the cleanest option is handling both at the same time (probably as a series of smaller changes with a clear "end state" in mind). Thoughts?

**Comment by tychoish** [comment]
I'd definitely do the lock untangling first and then split things out but you could interleave them into different commits/PRs. 

I think having some kind of base integration test for guard rails would be good, as a prerequisite for both.

**Comment by sharnoff** [comment]
This is (presumably) no longer applicable -- there's been a lot of changes in the last year and a half :)
