### ISSUE TITLE
Scheduler uses >1 CPU without load

### ISSUE THREAD

**Issue by sharnoff** [neondatabase/autoscaling#39]
Just noticed this, not sure how often it occurs or what triggers it. `perf` seemed to indicate it was just doing runtime operations, so maybe there's some kind of concurrent live-loop going on? More investigation required.

**Comment by tychoish** [comment]
Can you post/attach the pprof dump?

**Comment by sharnoff** [comment]
Just noticed it's more typically using 1.36 CPU (yes, exactly that) — regular "create cluster" reproduces, and it's also like this on staging. Kind of embarrassing this wasn't noticed sooner - I'll recompile with pprof and paste info here.
