### ISSUE TITLE
Epic: Find the way to connect to static port from VM-informant

### ISSUE THREAD

**Issue by vadim2404** [neondatabase/autoscaling#420]
It's needed to create a network policy to limit the network visibility scope for VMs

**Comment by fprasx** [comment]
Plan for week of 31JUL2023:
* Merge @hlinnaka  PR (#447) for an immediate fix
* After @fprasx is finished refactoring the monitor, prepare (#442) for merge. This will require restarting all VMs but is a longer term fix.
