### ISSUE TITLE
Bug: NeonVM compute got OOM and wasn't restarted automatically

### ISSUE THREAD

**Issue by ololobus** [neondatabase/autoscaling#446]
One NeonVM became unresponsive for 30 mins today on prod and got force-suspended
```{"level":"WARNING","ts":"2023-07-28T13:32:05.538Z","logger":"background_worker.activity_monitor","message":"endpoint is marked as active, but compute doesn't respond for more than 30m0s, scheduling the force suspend...","trace_id":"jzXM3Xpjqr7w3AccPMLA3m","source":"background_worker","worker_type":"activity_monitor","worker_index":2,"project_id":"wandering-poetry-850954","branch_id":"br-rapid-glade-105190","endpoint_id":"ep-wild-bush-796232","last_active":"2023-07-28T12:27:51.469Z","updated_at":"2023-07-28T13:31:48.277Z"}```

Here is the compute https://console.neon.tech/admin/computes/compute-crimson-leaf-98092157 from this period

```log
[ 9489.281515] RSP: 002b:00007ffced628c58 EFLAGS: 00010246
[ 9489.280928] Code: Unable to access opcode bytes at RIP 0x4d3658.
[ 9489.280540] RIP: 0033:0x00000000004d3682
[ 9489.276764]  0xffffffffbc49eb16
[ 9489.276451]  0xffffffffbcb65f47
[ 9489.276139]  0xffffffffbcb5e92e
[ 9489.275827]  0xffffffffbcb700f0
[ 9489.275507]  0xffffffffbcb700cb
[ 9489.275295]  <TASK>
[ 9489.273963] Hardware name: QEMU Standard PC (Q35 + ICH9, 2009), BIOS rel-1.16.0-0-gd239552ce722-prebuilt.qemu.org 04/01/2014
[ 9489.273285] CPU: 0 PID: 1 Comm: init Tainted: G        W         5.15.80 #1
[ 9489.272648] Kernel panic - not syncing: System is deadlocked on memory
[ 9489.272144] Out of memory and no killable processes..
```
https://neonprod.grafana.net/goto/ylb7H13VR?orgId=1

I also wonder why VM wasn't restarted by NeonVM k8s controller after OOM? Pods are restarted by deployment controller in this case and although OOM is annoying, it's not that critical as compute will be back alive very soon

**Comment by cicdteam** [comment]
will try with `panic=-1` kernel param ti mitigate this issue.
