### ISSUE TITLE
Bug: Memory scaling breaks with "attempt to add duplicate property 'memslot<N>' ..."

### ISSUE THREAD

**Issue by sharnoff** [neondatabase/autoscaling#451]
## Environment

Local testing while trying to reproduce the kernel panic (#450). A quick search shows it's widely present in prod as well.

## Steps to reproduce

There's a handful of ways to do this. But broadly having some kind of memory usage in the VM that prevents downscaling memory + continually scaling up & down memory slots[^memory-slots] (manually; not via autoscaling) will result in the error. I used some of the stuff from https://github.com/neondatabase/autoscaling/issues/450#issuecomment-1678074941. Here's an example of the error:

```
attempt to add duplicate property 'memslot10' to object (type 'container')
```

... which typically occurs after many rounds of these:

```
All memory devices busy, unable to unplug any, will modify .spec.guest.memorySlots.use instead
```

NB: in this example, 'memslot10' shouldn't ever be used — I was using a VM with `spec.guest.memorySlots.max = 10` so there should only be memslots 0 through 9, but because `qom-list` is returning a value for all memory slots (even if not all of them are actually in use), then we make it through this loop without finding anything (and use `slots + 1` as the id):

https://github.com/neondatabase/autoscaling/blob/f622fd96a3106d8a432f3b2f345c76d084020262/neonvm/controllers/virtualmachine_qmp_queries.go#L354-L370

I suspect that either (a) our usage of qom-list is incorrect (maybe presence via qom-list doesn't necessarily mean it's online?), or (b) QEMU's behavior is incorrect.

## Expected result

We should continue scaling up and down as normal, subject to occasionally not being able to unplug a memory slot.

## Actual result

We gradually exhaust all memory slots, and because of an off-by-one error end up repeatedly failing with this "attempt to add duplicate property" error, which prevents adding any further memory slots. I think _maybe_ the situation self-resolves when the memory usage drops lower AND it coincides with requesting to unplug memory, but I'm not sure.

[^memory-slots]: For specifics: I was using 0.1 CPU (larger CPU means the problem is less likely to occur) and alternating between 2 and 3 memory slots, 5s apart. I was using the `allocate-loop` binary that's included in `postgres14-disk-test`, run as `allocate-loop 1024 1536`, which _doesn't_ get OOM-killed during normal operation at 2 memory slots, but _does_ when scaling.

**Comment by Omrigan** [comment]
I've successfully reproduced the issue with the following:
<details>
<summary>
repro-loop.sh
</summary>
```VM_NAME=postgres14-disk-test
MIN=2
MAX=3
DELAY='5s'

submit_patch_mem () {
    slots="$1"

    patch='[{
        "op": "replace",
        "path": "/spec/guest/memorySlots/use",
        "value": '"$slots"'
    }]'

    echo -n "patching to $slots memory slots... "
    kubectl patch neonvm "$VM_NAME" --type=json --patch "$patch"
}

submit_patch_both () {
    cu="$1"

    patch='[
        {
            "op": "replace",
            "path": "/spec/guest/cpus/use",
            "value": '"$cu"'
        },
        {
            "op": "replace",
            "path": "/spec/guest/memorySlots/use",
            "value": '"$cu"'
        }
    ]'

    echo -n "patching to $cu CU... "
    kubectl patch neonvm "$VM_NAME" --type=json --patch "$patch"
}

# VERSION A: Didn't work.
# while true; do
#     slots=$(( $RANDOM % ($MAX - $MIN + 1) + $MIN ))
#     submit_patch_mem "$slots"
#
#     sleep "$DELAY"
# done

# VERSION B: Maybe closer? Easier to get bad behavior.
while true; do
    submit_patch_mem "$MIN"
    sleep "$DELAY"
    submit_patch_mem "$MAX"
    sleep "$DELAY"
done

# VERSION C:
# while true; do
#     submit_patch_both "$MIN"
#     sleep "$DELAY"
#     submit_patch_both "$MAX"
#     sleep "$DELAY"
# done````
</details>

<details>
<summary>
vm-deploy-tiny.yaml
</summary>
```
---
apiVersion: vm.neon.tech/v1
kind: VirtualMachine
metadata:
  name: postgres14-disk-test
  annotations:
    # In this example, these bounds aren't necessary. So... here's what they look like :)
    autoscaling.neon.tech/bounds: '{ "min": { "cpu": 0.1, "mem": "1Gi" }, "max": { "cpu": 1.25, "mem": "5Gi" } }'
  labels:
    autoscaling.neon.tech/enabled: "false"
    # Set to "true" to continuously migrate the VM (TESTING ONLY)
    autoscaling.neon.tech/testing-only-always-migrate: "false"
spec:
  schedulerName: autoscale-scheduler
  guest:
    cpus: { min: 0.1, use: 0.1, max: 1.25 }
    memorySlotSize: 1Gi
    memorySlots: { min: 1, use: 1, max: 5 }
    rootDisk:
      image: pg14-disk-test:dev
      size: 8Gi
    ports:
      - port: 22   # ssh
      - port: 5432 # postgres
      - port: 9100 # metrics
      - port: 10301 # monitor
```
</details>

Therefore, with only 5 slots, the error message is 
```
Failed to reconcile (postgres14-disk-test): attempt to add duplicate property 'memslot5' to object (type 'container')
```

**Comment by Omrigan** [comment]
> NB: in this example, 'memslot10' shouldn't ever be used — I was using a VM with spec.guest.memorySlots.max = 10 so there should only be memslots 0 through 9

I think they are numbered 1 through 10. 
```
slots := *virtualmachine.Spec.Guest.MemorySlots.Max - *virtualmachine.Spec.Guest.MemorySlots.Min
// slots := 9
```
Therefore, after we finish the loop, `slot = 10`, but `memslot10` is still a valid name to create the object (if it is not occupied already).

The early return in this function happens, when `{"execute": "query-memory-devices"}` equals to slot number limit. The number of **memory devices** can be less than max, but the number of **memory objects** can be max already. This might happen if during the unplug the device was removed, but the object was not.  

I've managed to capture this state of VM:
```
{"execute": "query-memory-devices"}
{"return": [{"type": "dimm", "data": {"memdev": "/objects/memslot5", "hotplugged": true, "addr": 5368709120, "hotpluggable": true, "size": 1073741824, "slot": 1, "node": 0, "id": "dimm5"}}]}

{"execute": "qom-list", "arguments": {"path": "/objects"}}
{"return": [{"name": "type", "type": "string"}, {"name": "memslot1", "type": "child<memory-backend-ram>"}, {"name": "memslot4", "type": "child<memory-backend-ram>"}, {"name": "memslot2", "type": "child<memory-backend-ram>"}, {"name": "memslot5", "type": "child<memory-backend-ram>"}, {"name": "pc.ram", "type": "child<memory-backend-ram>"}, {"name": "memslot3", "type": "child<memory-backend-ram>"}]}
```

I will proceed with trying to figure out why we have leftover objects, with no corresponding device.

**Comment by sharnoff** [comment]
Status: blocked on review from @sharnoff and @shayanh.
