### ISSUE TITLE
Bug: VM fractional CPU >1 always scales on startup

### ISSUE THREAD

**Issue by sharnoff** [neondatabase/autoscaling#452]
## Environment

Local development

## Steps to reproduce

Edit `vm-deploy.yaml` to have `spec.guest.cpus.use = 1.25`.

Run:

```sh
kubectl apply -f vm-deploy.yaml && kubectl get -w neonvm
```

When I did this, I got:

```
virtualmachine.vm.neon.tech/postgres14-disk-test created
NAME                   CPUS   MEMORY   POD                          EXTRAIP   STATUS    AGE
postgres14-disk-test                   postgres14-disk-test-2pqmw             Pending   0s
postgres14-disk-test                   postgres14-disk-test-2pqmw             Running   5s
postgres14-disk-test   1      1Gi      postgres14-disk-test-2pqmw             Scaling   5s
postgres14-disk-test   1      1Gi      postgres14-disk-test-2pqmw             Running   5s
postgres14-disk-test   1250m   1Gi      postgres14-disk-test-2pqmw             Running   5s
```

## Expected result

We should see that the VM is created, pending, and then has 1250m CPUs and 1Gi memory, in that order, without intermediate steps.

## Actual result

The VM initially has 1 CPU and 1Gi memory, and then enters the "Scaling" phase and increases to 1250m CPUs.

**Comment by cicdteam** [comment]
yes, it by design and i see no other ways. 

if you run VM with 1/2/4 cpus (min/use/max) QEMU started with `-smp cpus=1,maxcpus=4`. After that controller check `cpus.use` and hot-plugging one more cpu.

**Comment by sharnoff** [comment]
Realized I never replied. Closing, at least for now. We _may_ want to invest effort into this in the future, but the benefit is probably small.
