### ISSUE TITLE
Bug: VM memory scale-up leaves "Scaling" phase before updating status resources

### ISSUE THREAD

**Issue by sharnoff** [neondatabase/autoscaling#453]
## Environment

Local development

## Steps to reproduce

Start VM with e.g. 1 memory slot, 0.1 CPUs. In one window, run `kubectl get -w neonvm`, and in another (while the first is ongoing), increase the memory slots:

```sh
kubectl patch $VM --type=json --patch '[{"op": "replace","path": "/spec/guest/memorySlots/use","value": 2}]'
```

The output of the `kubectl get -w` ("watch") shows something like:

```
postgres14-disk-test   100m   1Gi      postgres14-disk-test-295fb             Running   26s
postgres14-disk-test   100m   1Gi      postgres14-disk-test-295fb             Running   54s
postgres14-disk-test   100m   1Gi      postgres14-disk-test-295fb             Scaling   54s
postgres14-disk-test   100m   1Gi      postgres14-disk-test-295fb             Running   54s
postgres14-disk-test   100m   2Gi      postgres14-disk-test-295fb             Running   54s
```

## Expected result

The VM should leave the "Scaling" phase only once the resource usage in the status has been adjusted. (either at the same time, or after).

This isn't a _super_ important (especially because k8s is eventually consistent), but IMO the resource usage should not change unless we're in the "Scaling" phase.

## Actual result

The VM's phase is set to "Running" before the resources are updated.

## Links
- #350

**Comment by shayanh** [comment]
This is intended. I mean it's not a bug and NeonVM controller intentionally works this way. Here is how NeonVM controller reconcile loop works given a VM object.

If VM is in `Running` phase, then update the resource values in status and update the status to  `Scaling`, if needed.
If VM is in `Scaling` phase, then update QEMU and cgroup stuff. If successful then update the status to `Running`. Note that *we don't update status resource values here*.

So here is the trace:

1. `vm.Status.Phase = Running` -> update `vm.Status.Phase` to `Scaling`.
2. `vm.Status.Phase = Scaling` ->  update qemu and cgroups, and update `vm.Status.Phase` to `Running`.
3. `vm.Status.Phase = Running` -> update `vm.Status.CPUs` and `vm.Status.MemorySize`.

I'd say this is not high priority issue. We can update the `vm.Status.CPUs` and `vm.Status.MemorySize` value while in the `Scaling` phase. I gotta think how to do it without breaking anything or making things more complicated.

**Comment by sharnoff** [comment]
Status: waiting on further review from @cicdteam
