### ISSUE TITLE
agent: deduplicate scheduler watchers

### ISSUE THREAD

**Issue by sharnoff** [neondatabase/autoscaling#5]
Currently we create a new Watch for each pod that the autoscaler-agent handles. That's not _ideal_, but we can live with it for a little while.

See also: https://github.com/neondatabase/autoscaling/pull/4

**Comment by tychoish** [comment]
https://github.com/neondatabase/autoscaling/commit/4a48622fb7e7963308eadb8bb0931dbf99c2a663
