### ISSUE TITLE
Make CI faster

### ISSUE THREAD

**Issue by shayanh** [neondatabase/autoscaling#660]
## Problem description / Motivation

As of now, the entire CI process [takes about 20 minutes](https://github.com/neondatabase/autoscaling/actions/runs/7066178893/job/19237582034?pr=649), which is not the worst thing in the world but still it's long and annoying. 

## Feature idea(s) / DoD

As a starting point, a DoD can be decreasing CI time to less than 10m.

## Implementation ideas

Most expensive parts of the pipeline are `make kernel` and `make example-vms`, which I think we can use pre-built image and avoid building them every time.

**Comment by bayandin** [comment]
https://github.com/neondatabase/autoscaling/pull/661 brings e2e-test workflow to around 10m.
https://github.com/neondatabase/autoscaling/pull/642 shaves off another 1.5m

**Comment by sharnoff** [comment]
Since merging #748, _at first glance_ it appears e2e-test times are around 8-9 minutes (at least, when there's no contention for runners).

@shayanh wdyt, is this done? should we wait a little longer to validate e2e-test times are still low?

**Comment by shayanh** [comment]
<10 is nice. Great progress. I close the issue. We can re-open if the times go up again.
