### ISSUE TITLE
local k8s clusters (kind and k3d) should have $USER in name

### ISSUE THREAD

**Issue by cicdteam** [neondatabase/autoscaling#676]
## Problem description / Motivation

Currently, `make kind-setup` creates a cluster named `kind-kind`, and `make k3d-setup` creates `k3d-neonvm`. On shared servers will be a mess if multiple users run local clusters.

## Implementation ideas

Add `$USER` to the local cluster name to avoid confusion.

cc: @sharnoff @shayanh

**Comment by sharnoff** [comment]
@cicdteam this was fixed in #677, IIUC?
