### ISSUE TITLE
Bug: Cannot access NeonVM pods metrics endpoint

### ISSUE THREAD

**Issue by shayanh** [neondatabase/autoscaling#692]
## Environment

local development, staging

(idk if it's the case in prod)

## Steps to reproduce

```
kubectl --context dev-us-east-2-beta port-forward compute-wispy-surf-w25ffuy9-hwvdf 9100:9100
```

and then `curl http://localhost:9100/metrics` gets stuck.

## Expected result

Seeing metrics via curl.

## Actual result

No response.

**Comment by shayanh** [comment]
I investigated this, and it's not a bug; it just doesn't work as I expected. We do port-forwarding from the pod to the running qemu process running inside using iptables pre-routing DNAT rules. As a result, it only applies to the traffic coming from an external interface (i.e., not loopback). So if you go inside the pod and run `curl localhost:9100/metrics`, you get nothing. However, if you try `curl podIP:9100/metrics` from another pod, you get the response back.

This has been fine so far, but some stuff won't work as expected. For example, if a pod has exposed port 9100, I expect to be able to do port-forwarding on that (as mentioned above). I played around with iptables a bit but couldn't write the right set of rules to handle this.

@cicdteam I saw you wrote this part of the code. What do you think?

**Comment by vadim2404** [comment]
@cicdteam to help here
