### ISSUE TITLE
Bug: autoscaler-agent scaling algorithm is too volatile for larger computes

### ISSUE THREAD

**Issue by sharnoff** [neondatabase/autoscaling#729]
## Problem description / Motivation

One of the blockers for allowing larger computes (ref neondatabase/cloud#9103) is improving the scaling algorithm.

Currently, because the scaling algorithm (a) recalculates the "goal" CU every 5s, via updated metrics, and (b) does not factor into account past metrics when calculating the "goal" CU:

1. It's easy to cause the goal CU to oscillate, resulting in a lot of effort spent scaling, with little net benefit
2. As computes get larger, the same percentage change in metrics is more likely to produce a change in (integer) goal CU — meaning that each 5s the metrics update is more likely to prompt scaling, and by a larger amount

In a perfect world, maybe this'd be fine. But in practice, the process of scaling actually consumes resources, and so is _generally_ something we want to avoid doing frivolously.

See also: https://neondb.slack.com/archives/C03ETHV2KD1/p1704319422570509?thread_ts=1704316837.680979

## Feature idea(s) / DoD

Scaling algorithm should be more stable over _some_ time period, under _some_ conditions.

This isn't a super well-defined goal — so this issue mostly just exists to track _some_ improvement.

## Implementation ideas

There's a couple directions we could take this.

One is to _still_ not include any scaling history, and instead limit the size of a change (e.g., by no more than 1 CU at a time) and introduce rate-limiting on scaling. This wouldn't necessarily stop oscillation, but may reduce the impact.

The other is to include some history around recent metrics so that we have a longer time period to use for decision-making. This solution would probably be harder, but likely easier to understand and easier to produce better outcomes.

One _possibly_ annoying piece of this is that we may need to change a substantial portion of the tests for `pkg/agent/core`. We probably want a way to override the "goal CU" and directly provide that.

## Tasks

```[tasklist]
# Pre-requisites
- [ ] #1129
```

```[tasklist]
# Implementation
- [ ] ... add tasks here as they come up
```

```[tasklist]
# Follow-ups
- [ ] ... add tasks here as they come up
```

**Comment by sharnoff** [comment]
There's an open RFC that will _partially_ address this issue here: https://www.notion.so/neondatabase/131f189e004780b2915ef2fdb95bae6a

In short: the approach should reduce volatility by ~60% from what we have today, but it's only a fractional decrease — probably insufficient for very volatile workloads on _much_ larger computes.

**Comment by Omrigan** [comment]
Testing #1148 


Here is ZoneLoadAverage with stable_ratio=0.25 and mixed_ratio=0.25
[![Image](https://github.com/user-attachments/assets/02c5a6b0-626f-400d-b683-b924f73ff5cb)
](https://neonprod.grafana.net/goto/ZN9Z8fnHR?orgId=1)

Baseline:
![Image](https://github.com/user-attachments/assets/54ac97ff-3664-4fba-afa3-edd4a516b703)



Workload is `i=0; T=10; while [ $i -lt 1800 ] ; do pgbench -c160 -j40 -b select-only -T$T $CONNSTR; s=$(( $RANDOM % 5 )); sleep $s; i=$(( $i + $s + $T )); done`
