### ISSUE TITLE
Merge auxillary containers to reduce pressure on container runtime

### ISSUE THREAD

**Issue by Omrigan** [neondatabase/autoscaling#747]
https://github.com/neondatabase/autoscaling/issues/711#issuecomment-1893637974 suggests there is no system in how long every container takes to be created/started. 

This can be explained by the fact that `containerd` has to create and run each container. In the peaks it might be overwhelmed, thus sporadic queues might occur.  

The idea is to reduce the number of containers. In the best case we need only one - main container with QEMU.

**Comment by sharnoff** [comment]
A couple notes:

1. IIRC there's three reasons we require init containers:
    1. To make image loading easier (see `init-rootdisk`, or [when using a custom kernel] `init-kernel`)
    2. To perform privileged operations without giving `neonvm-runner` those privileges (see `neonvm-runner`)
    3. For setting up iptables rules externally (cplane injects an extra init container to do this, because (a) it's not natively supported by neonvm, and (b) using an init container means the process is the same for k8s-pod computes)
2. Given this, there's several reasons in practice we may need to keep _at least_ one init container. But I'm generally +1 to reducing the number of init containers where we're able to.

**Comment by Omrigan** [comment]
As the result of discussions with @sharnoff and @ololobus I intend to do the following changes:
1. Merge `init-rootdisk` and `sysctl` containers (#769)
2. Move iptables configuration logic from `compute-init` to `neonvm-runner`, thus dropping `compute-init`
3. Get rid of the `init` container by:
  a. Merging compute and `runner` images, so there is no need to copy disk
  b. Configuring parent network namespace, so that sysctl is not needed

**Comment by sharnoff** [comment]
status: Two PRs are ready (#769 and #782), need review on those. Planning to open a follow-up to #782 to refactor neonvm-runner.

**Comment by sharnoff** [comment]
status: #769 and #782 still pending, reviewed & need to reply. #790 opened and should help as well, WIP.
Previously blocked on deploy of startup metrics; they aren't yet on prod, but should be this week.

**Comment by Omrigan** [comment]
#769 is in production since yesterday, and the graph suggests 1s reduction it timings (at least for the fastest ones): 

![screenshot-2024-02-23_02-19-30_504387060](https://github.com/neondatabase/autoscaling/assets/2663743/0a3b57d4-ac71-4e45-9cc3-76123755a98c)

#782 is merged, but the enablement on cplane side is WIP: https://github.com/neondatabase/cloud/pull/10630

#790 is still WIP.
