### ISSUE TITLE
Epic: VM startup latency metrics & SLOs

### ISSUE THREAD

**Issue by sharnoff** [neondatabase/autoscaling#759]
## Motivation

Startup latency has downstream effects that easily become visible to users in the form of start_compute latency.

We should minimize this where possible — and we need observability and alerting to track progress and make sure we don't regress.

## DoD

The time between VirtualMachine object creation and QEMU bootup complete is accurately represented by a metric exposed by the neonvm-controller, with SLOs and alerting based on it.

## Implementation ideas

With #754, we could add a histogram metric that we add to exactly when the VM goes to the `Running` phase with `.Status.Restarts == 0` — we'd use the difference between `time.Now()` and `.Metadata.CreationTimestamp`. This would _probably_ be good enough, but may miss certain kinds of metrics.

## Tasks

```[tasklist]

```

## Other related tasks, Epics, and links

- #594

**Comment by shayanh** [comment]
I'm planning to add the following metrics to the NeonVM controller:
1. `vm_creation_to_runner_creation_duration`: VM creation timestamp to runner pod creation timestamp
2. `runner_creation_to_vm_running_duration`: Runner pod creation timestamp to the moment when NeonVM controller changes VM's status to Running from Pending.

Note that the second metric is not quite precise due to #771.

**Comment by sharnoff** [comment]
status: Had a PR implementing this, was blocked on a PR by @sharnoff, but now that's merged this can continue. Plan to merge this week

**Comment by sharnoff** [comment]
status: Metrics are merged & on staging. There's a [notion doc](https://www.notion.so/neondatabase/Autoscaling-Alerts-4f793e2822114465a10b4cf7daeaa57d) for planning what alerts we should have. Waiting on deploy -> prod to get a sense of numbers for the SLOs.

**Comment by shayanh** [comment]
Done. Has been discussed here in [Autocaling alerting Notion doc](https://www.notion.so/neondatabase/Autoscaling-Alerts-4f793e2822114465a10b4cf7daeaa57d).

**Comment by sharnoff** [comment]
@shayanh should this issue be closed?

**Comment by shayanh** [comment]
Yes, I close it.
