### ISSUE TITLE
auto-convert endpoints to k8s-neonvm on restart

### ISSUE THREAD

**Issue by stradig** [neondatabase/autoscaling#772]
The actual work in on the control plane team and tracked in the link Shayan added.

**Comment by shayanh** [comment]
Tracking here: https://github.com/neondatabase/cloud/issues/10462

**Comment by sharnoff** [comment]
@shayanh should we close in favor of neondatabase/cloud#10462 and refer to that instead in neondatabase/company_projects#187 ?

**Comment by shayanh** [comment]
let's do it
