### ISSUE TITLE
could not resize shared memory segment with pgvector 0.6.0

### ISSUE THREAD

**Issue by hlinnaka** [neondatabase/autoscaling#800]
## Problem

pgvector v0.6.0 introduced new in-memory parallel index build mechanism. It allocates a large block of dynamic shared memory at the beginning of the block as working area. The size of the allocation is defined by `maintenance_work_mem`. PostgresQL makes the dynamic shared memory allocation essentially by creating a file under /dev/shm.

The default size of /dev/shm in Linux is 1/2 of physical memory. Our VMs start with a small amount of physical memory, so they have a small limit on /dev/shm. As a result, if maintenance_work_mem is set larger, the index build fails: 

```
neondb=> set maintenance_work_mem to '16000 MB';
SET
neondb=> SET max_parallel_maintenance_workers = 8;
SET
neondb=> CREATE INDEX ON documents USING hnsw (openai_vector vector_l2_ops) WITH (m = 16, ef_construction = 64);
ERROR:  could not resize shared memory segment "/PostgreSQL.2892504480" to 16774205952 bytes: No space left on device
```

This is blocking upgrading to pgvector v0.6.0

## Expected outcome

- The index build should not fail with default settings
- You should be able to set `maintenance_work_mem` to a higher value without failing.
- You should be able to use most of the memory available, up the Max autoscaling limit, for the index build.

## Current plan

- Add a swap disk to the VMs. Size: 1 /2 of the max autoscaling limit
- Increase size of /dev/shm to that size
- Add "the system is swapping" as a condition to autoscale 

## References

internal slack discussion: https://neondb.slack.com/archives/C03QLRH7PPD/p1706867424699999

**Comment by hlinnaka** [comment]
This is an acute problem with pgvector 0.6.0, but another operation that can make a large dynamic shared memory allocation is parallel VACUUM of a large table.

**Comment by hlinnaka** [comment]
I did some testing of this locally. Unfortunately, it seems that the swap-approach will not work, not without problems anyway :-(.

My test setup is a VM with that starts 4 GB of memory attached, and 32 GB of swap:
```
top - 23:30:56 up 2 min,  0 users,  load average: 0.18, 0.06, 0.01
Tasks:  80 total,   2 running,  78 sleeping,   0 stopped,   0 zombie
%Cpu(s):  6.2 us,  6.2 sy,  0.0 ni, 81.2 id,  6.2 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :   3990.6 total,   3815.5 free,    109.7 used,     65.4 buff/cache
MiB Swap:  32768.0 total,  32687.9 free,     80.1 used.   3840.0 avail Mem 
```

Creating a 10 GB under /dev/shm with dd succeeds:
```
root@neonvm:~# dd if=/dev/urandom of=/dev/shm/xxx bs=1G count=10
10+0 records in
10+0 records out
10737418240 bytes (11 GB, 10 GiB) copied, 53.2719 s, 202 MB/s
```

But HNSW index build in PostgreSQL still fails:
```
neondb=> SET maintenance_work_mem='5 GB';
SET
neondb=> reindex index items_small_embedding_idx ;
ERROR:  could not resize shared memory segment "/PostgreSQL.2012241406" to 5365600384 bytes: Cannot allocate memory
```

I can reproduce that with a small test C program that uses open(2) to create a file under /dev/shm, and then enlarge it with posix_fallocate(3). PostgreSQL uses shm_open(3), which is equivalent to creating a file under /dev/shm, and then uses posix_fallocate(3).

So there is a difference between enlarging the file with one posix_fallocate(3) call, or with smaller writes like `dd` does. One posix_fallocate() call that's larger than the available (physical, non-swap) memory fails with ENOMEM, but doing it with smaller writes succeeds.

Found this thread on linux-mm mailing list discussing the same issue:

https://lore.kernel.org/linux-mm/20190219041650.GB15503@dastard/T/#mffbf88ddf22bebf26647cbe6919360fe5dd92aa5

**Comment by hlinnaka** [comment]
I can see three main options for how to proceed from here, with some variants:

### 1. Salvage the swap approach

Work around the ENOMEM on posix_fallocate() call somehow, making the swap approach work the way we intended.

a) Modify Postgres to use multiple smaller posix_fallocate() calls, instead of one big one.

b) Modify Linux kernel to allow a large fallocate(), as long as there's swap to back it

### 2. Set dynamic_shared_memory_type=mmap

With this approach, the large shared memory allocation is a file on a
regular filesystem, not /dev/shm.

Per PostgreSQL docs:

> The use of the mmap option, which is not the default on any platform, is generally discouraged because the operating system may write modified pages back to disk repeatedly, increasing system I/O load; however, it may be useful for debugging, when the pg_dynshmem directory is stored on a RAM disk, or when other shared memory facilities are not available.

So with that, the kernel will try to keep the memory pages backing the
allocation clean, writing the dirty pages back. Once the amount of dirty pages hits 'dirty_ratio', the process will be throttled. HNSW index build is very random, so we will hit that quickly.

a) Accept the higher write I/O rate. Maybe it's OK in practice.

b) Increase 'dirty_ratio' and 'dirty_expire_centisecs'

If we set them high enough, the kernel will be less aggressive in cleaning the dirty pages, reducing the I/O.

The downside of setting these very high is that it can make the performance more uneven during normal usage. Maybe it's OK, given our workload. The same considerations apply to our local file cache, too.

### 3. Modify pgvector to allocate the memory as you go

Instead of one huge allocation, allocate the memory in smaller chunks as needed. This would be a good thing for upstream pgvector too. See discussion at https://github.com/pgvector/pgvector/issues/434.

This will take some time to develop, and could turn out to not be feasible. Also, this will not help with other large DSM allocations, like with large parallel vacuums.

**Comment by hlinnaka** [comment]
Looking at the Postgres DSM code, there is a small difference between 'mmap' and 'posix' dynamic_shared_memory_type options: with 'posix', it uses posix_fallocate() to enlarge the file, but with 'mmap', it uses write(2) in a loop. So we might be able to make the swap approach work, after all, if we set `dynamic_shared_memory_type=mmap`, but then symlink the pg_synshm directory to /dev/shm. Weird, but I'll give that a try.

**Comment by hlinnaka** [comment]
Bumped into one more speedbump with that  plan with 'mmap': a Postgres bug in that implementation: https://www.postgresql.org/message-id/flat/18341-ce16599e7fd6228c%40postgresql.org. I pushed a fix to that to upstream, but we'll need to cherry-pick it to neon earlier if we go with that approach.

**Comment by sharnoff** [comment]
Latest ongoing work:

- neondatabase/autoscaling#886
- neondatabase/neon#7239 (requires the first)

**Comment by wahajali** [comment]
@hlinnaka is this an issue with pgvector version 0.6.0 only or was it fixed on later versions. I noticed this issue as well on v0.6.0, but found it to work fine on a different system that had v0.6.1.
I had the following:
`10M vectors, 768 dimensions`
`4 vCPU and 16 GB ram`
`shared buffer = 5 GB`
`maintenance_work_memory = 7GB`
`max_parallel_maintenance_workers = 2`

**Comment by hlinnaka** [comment]
H @wahajali! There should be no difference between v0.6.0 and v0.6.1 on this. Perhaps you had something else running and consuming memory in one case but not the other? With those settings, there should be some headroom for other things (5 GB + 7 GB = 12 GB < 16 GB), but maybe not enough.

**Comment by sharnoff** [comment]
This issue has been fixed by enabling swap (among a few other related changes).
Internal issue comment here: https://github.com/neondatabase/cloud/issues/12047#issuecomment-2159315930
