### ISSUE TITLE
Bug: autoscaler-agent's vm-monitor inbound messages metric isn't working

### ISSUE THREAD

**Issue by sharnoff** [neondatabase/autoscaling#807]
## Environment

staging, prod. Presumably also local dev

## Steps to reproduce

Gradually use up memory, e.g. with pgvector 0.5.1 index building, causing the vm-monitor to request upscaling.

## Expected result

the metric `autoscaling_agent_monitor_inbound_requests_total` should be non-zero because of this

## Actual result

the metric doesn't change

## Other logs, links

- ...

**Comment by Omrigan** [comment]
@sharnoff should we create a follow-up issue to investigate if it is possible to set up a linter for this case?

**Comment by sharnoff** [comment]
Good idea - opened #842.
