### ISSUE TITLE
Better VM metrics for scaling signals

### ISSUE THREAD

**Issue by sharnoff** [neondatabase/autoscaling#81]
Making scaling decisions solely based on load average is... not great.

## Design notes

Some considerations:

* Load average is slow to respond, but it _does_ measure something useful
  * load average is weird. See also: https://www.brendangregg.com/blog/2017-08-08/linux-load-averages.html
  * Maybe possible to de-average load average, to get a shorter time window? (e.g. "what's the 5-second load average?")
    * also _might_ be possible to patch the kernel for, but that's a lot of work for not much
* It'd be good to have memory available — e.g. if close to OOM, scale up!
  * Because the VM informant knows how much is allocated to each of: (1) postgres, (2) file cache, (3)  system, it can indicate that postgres is running out of memory, even if total memory usage is relatively low.

## Implementation notes

It's probably possible to get memory info from the prometheus metrics we're already using. Other changes would probably amount to adding another field to [`pkg/api.InformantMetricsMethod`](https://github.com/neondatabase/autoscaling/blob/d827683eda8c92895e44bf394077807e41cd7562/pkg/api/types.go#L394-L404), and appropriately threading that ambiguity through everywhere.

Any solution should probably continue to give the scheduler the load average numbers ­— it uses them for ranking migration priority, which seems reasonable to me. It _does_ have a way to "veto" migration if metrics changed too much — LA on a shorter time window could be useful there (see [`(*pkg/plugin.podState).checkOkToMigrate`](https://github.com/neondatabase/autoscaling/blob/d827683eda8c92895e44bf394077807e41cd7562/pkg/plugin/state.go#L387-L395))

A final note on memory: the external memory allocated (e.g. 4GiB) won't match the observed amount inside the VM, because the kernel subtracts the memory it's using from the reported total memory. Last I checked, that was ~100MiB for the test VM.

**Comment by stradig** [comment]
We will handle the rest of the work as part of other work (#849 ).
