### ISSUE TITLE
Epic: Solving the “pgvector 0.6” problem

### ISSUE THREAD

**Issue by stradig** [neondatabase/autoscaling#848]
## Motivation
TODO

## Implementation ideas

TODO

## Tasks

```[tasklist]
- [ ] ...
- [ ] List tasks as they're created for this Epic
```

## Other related tasks, Epics, and links

-

**Comment by sharnoff** [comment]
I think this is a duplicate of #800 ?

**Comment by stradig** [comment]
Right, this is a duplicate. Probably does not make sense to have both. Closing this.
