### ISSUE TITLE
Bug: scheduler's critically delayed event processing has positive feedback loop

### ISSUE THREAD

**Issue by sharnoff** [neondatabase/autoscaling#851]
## Environment

Prod (occurred twice recently)

## Steps to reproduce

Hard to reproduce locally - requires odd circumstances under a lot of load. AFAICT we've only seen it occur at startup — probably because that's when there's the most stuff going on.

The general idea of the triggering behavior is this:

1. For some reason, event processing in the scheduler gets delayed (whether that's because of weird behavior at startup, or some other failure mode)
2. _Some_ VM pod start events are delayed enough that the VMs are deleted before the events are handled
3. While handling those events:
    1. We don't see the VM in the local VM store (because it doesn't exist)
    2. Thinking the store is out of date, we `Relist()` — this can take ~2s
    3. After relisting, the VM is still not in the store, so we return error
4. Because relisting takes _so long_, more events get delayed, so we handle more pod start events after the VM was deleted, so we cause _even more_ delays

Note that this is _also_ because we only handle a single event at a time, so waiting for 2s handling one event holds up the entire queue.

(Originally, that's because otherwise we'd have to be careful to avoid out of order start/stop events - there's ways around this, though).

## Other logs, links

- [initial discussion in slack](https://neondb.slack.com/archives/C03TN5G758R/p1709923277096179)
- [logs link](https://neonprod.grafana.net/explore?schemaVersion=1&panes=%7B%22bdw%22:%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bcluster%3D%5C%22prod-us-west-2-eta%5C%22,namespace%3D%5C%22kube-system%5C%22,pod%3D%5C%22autoscale-scheduler-84696b4d94-2kwdd%5C%22%7D%20%7C%3D%20%5C%22autoscale-scheduler.handlers%5C%22%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22from%22:%221709922300000%22,%22to%22:%221709922600000%22%7D%7D%7D&orgId=1)

## Tasks

```[tasklist]
- [ ] #853
- [ ] #854
- [ ] #863
```

Skipping duplicate `Relist()`s is somewhat complex, but is provably a solution here. Processing events in parallel allows us to make the problem small enough that we never reach the critical threshold of a positive feedback loop.

**Comment by sharnoff** [comment]
Assigning @Omrigan and removing myself to reflect that remaining work will be via #863 (and #865), rather than #853.

**Comment by Omrigan** [comment]
Done via #863
