### ISSUE TITLE
Complete cold start dashboard

### ISSUE THREAD

**Issue by Omrigan** [neondatabase/autoscaling#860]
This one: https://neonprod.grafana.net/d/adciwu8qykkqod/vm-creation-to-vm-running-latency?orgId=1

The issues I see ATM:
1. Heatmap has fixed range even when there are no datapoints
2. Needs to be moved out of `/personal/shayan`, links from [overview dashboard](https://neonprod.grafana.net/d/adblr0h942l8gd/neon-autoscaling-overview?orgId=1&refresh=1m) added, etc.

**Comment by shayanh** [comment]
@Omrigan what's missing specifically?

**Comment by shayanh** [comment]
[Done](https://neonprod.grafana.net/d/adg35sd2lo2kgc/neon-autoscaling-vm-cold-start?orgId=1).
