### ISSUE TITLE
scheduler plugin should have metrics for time events spend waiting in the queue

### ISSUE THREAD

**Issue by sharnoff** [neondatabase/autoscaling#862]
## Problem description / Motivation

We don't have this internal queue in the scheduler that's critical to correct functioning, but no observability into whether the queue is actually healthy.

## Feature idea(s) / DoD

Scheduler plugin should have metrics exposed for queue wait duration, maybe similar to how neonvm-controller does it.

**Comment by Omrigan** [comment]
@sharnoff added new metrics to https://neonprod.grafana.net/d/adbt34laf8ni8f/neon-autoscaling-scheduler-plugin?from=1713951126014&to=1713961926014&var-environment=prod&var-datasource=ZNX49CDVz&var-cluster=All&var-node_group=main_m6id_metal&var-node=All&var-autoscaler_agent_pod_suffixes=All&orgId=1&refresh=1m, please review

**Comment by sharnoff** [comment]
Looks good! Had a couple quick thoughts, but not enough to block closing this issue. Can discuss next week
