### ISSUE TITLE
Expose current version and show it on dashboards

### ISSUE THREAD

**Issue by Omrigan** [neondatabase/autoscaling#881]
## Problem description / Motivation

Discussed during proxy architecture.

This would help with correlating releases with issues directly on dashboard  

## Feature idea(s) / DoD

Possible to estimate a number of each instance of each component with any versions from the grafana dashboard. 

## Implementation ideas

Expose a single metric.

**Comment by sharnoff** [comment]
Implemented this using `kube_pod_container_info`'s `image` label. Closing for now, unless there's further opinions.
