### ISSUE TITLE
neonvm-vxlan.yaml and neonvm-multus.yaml files are missing

### ISSUE THREAD

**Issue by william-lbn** [neondatabase/autoscaling#883]
Is there any guidance document for building neon on k8s?  

I followed https://github.com/neondatabase/autoscaling/blob/main/neonvm/README.md. 

```
wget https://github.com/neondatabase/autoscaling/releases/latest/download/neonvm-multus.yaml
--2024-03-29 14:25:26--  https://github.com/neondatabase/autoscaling/releases/latest/download/neonvm-multus.yaml
Resolving github.com (github.com)... 20.205.243.166
Connecting to github.com (github.com)|20.205.243.166|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github.com/neondatabase/autoscaling/releases/download/v0.27.0/neonvm-multus.yaml [following]
--2024-03-29 14:25:26--  https://github.com/neondatabase/autoscaling/releases/download/v0.27.0/neonvm-multus.yaml
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 404 Not Found
2024-03-29 14:25:27 ERROR 404: Not Found.
```

I am a neon beginner and very interested in neon. Please give me some guidance, thank you very much.

**Comment by william-lbn** [comment]
I followed  https://github.com/neondatabase/autoscaling/releases

![image](https://github.com/neondatabase/autoscaling/assets/10280419/863d761a-80ac-4702-a819-5fa90d293187)

I follow the steps below

1）kubectl apply -f multus.yaml 

2）kubectl apply -f whereabouts.yaml

3)  kubectl apply -f neonvm.yaml 

4)  kubectl  apply -f vmscrape.yaml

```
root@node1:~/serverless/neonvm/releases# kubectl  apply -f vmscrape.yaml
resource mapping not found for name: "autoscaling-components" namespace: "monitoring" from "vmscrape.yaml": no matches for kind "VMPodScrape" in version "operator.victoriametrics.com/v1beta1"
ensure CRDs are installed first
resource mapping not found for name: "neonvm-controller" namespace: "monitoring" from "vmscrape.yaml": no matches for kind "VMPodScrape" in version "operator.victoriametrics.com/v1beta1"
ensure CRDs are installed first
```

**Comment by sharnoff** [comment]
Hi! Thanks for opening an issue. This appears to be an outdated documentation issue — `neonvm-vxlan.yaml` and `neonvm-multus.yaml` were (IIRC) replaced by `multus.yaml` for local development and `multus-eks.yaml` for running in EKS.

For the release assets, some of the files produced are primarily for our internal use — like `vmscrape.yaml`. It won't work without VictoriaMetrics installed, but isn't strictly required.

---

Opened #906 to update the docs.
