### ISSUE TITLE
Should emit error/warning/etc when pod bypasses plugin

### ISSUE THREAD

**Issue by sharnoff** [neondatabase/autoscaling#93]
It's possible to bypass the scheduler plugin by explicitly setting the `.spec.node` field for a `Pod` — this messes up our bookkeeping, so it'd be good to have some kind of early warning signs if something's going on.

OTOH the main idea for this that comes to mind would be to modify the plugin's pod watcher so that - on Add - it checks that the pod doesn't (a) have a matching scheduler name, (b) already have a node assigned, and (c) not exist in the existing pods map.

**Comment by mikhail-sakhnov** [comment]
@sharnoff it looks like for the c) there is already check in the reserveResources:

```
	// If the pod already exists, nothing to do
	if _, ok := e.state.pods[util.GetNamespacedName(pod)]; ok {
		logger.Info("Pod already exists in global state")
		return true, &verdictSet{cpu: "", mem: ""}, nil
	}
```


Is it sufficient enough? 🤔 

For the a) and b) I send a PR #1037
