### ISSUE TITLE
Bug: scp into guest-vm doesn't work

### ISSUE THREAD

**Issue by Omrigan** [neondatabase/autoscaling#930]
## Steps to reproduce
```
> scp -v test guest-vm:/root/test
...
debug1: Sending subsystem: sftp
scp: Connection closed
...
```

## Expected result

Scp works out of the box

## Other logs, links

- ...

**Comment by kelvich** [comment]
Found one workaround:

inside vm: `apt update && apt install openssh-clients`
now you can scp with `-O` flag: `scp -O foo.txt guest-vm:~/`
