### ISSUE TITLE
Bug: /neonvm/bin/resize-swap: command not found

### ISSUE THREAD

**Issue by Bodobolero** [neondatabase/autoscaling#955]
## Environment
staging US-East-2

## Steps to reproduce

Run large pgvector indexing, see https://neondb.slack.com/archives/C0732L0A4AH/p1717588107776839?thread_ts=1717499447.241659&cid=C0732L0A4AH

## Expected result
Swap space is increased when necessary

## Actual result
Error message in compute log

sudo: /neonvm/bin/resize-swap: command not found

## Other logs, links
https://neonprod.grafana.net/goto/gT_JXPyIR?orgId=1

**Comment by Omrigan** [comment]
This is actually the correct behavior, but a confusing error message, see #958.
