### ISSUE TITLE
No graceful shutdown for NeonVMs

### ISSUE THREAD

**Issue by nikitakalyanov** [neondatabase/autoscaling#97]
## Steps to reproduce
Run pg_bench and then stop the compute under it. (there is a console test for that)

## Expected result
The pg_bench exits with an error

## Actual result
The pg_bench hangs

## Environment
Local, staging, probably prod too

## Logs, links
- https://neondb.slack.com/archives/C03TN5G758R/p1680010162787079

**Comment by sharnoff** [comment]
This was implemented by #133, see here: https://github.com/neondatabase/autoscaling/pull/133#discussion_r1160854514

**Comment by nikitakalyanov** [comment]
Thanks, the test now passes!
